[editor]
theme = "github_light_high_contrast"
mouse = true
cursorline = false
cursorlineopt = "number"  # highlight both number and

[editor.whitespace]
render = "none"

[editor.cursor-shape]
normal = "block"
insert = "block"
select = "block"

[keys.normal.space]
t = "open_theme_picker"

